### ISSUE TITLE
fuy.gg causing incompatibility issues

### ISSUE THREAD

**Issue by BJack0** [Aninuscsalas/wynncraft-101#15]
After launching the pack for the first time, every subsequent launch is stopped by fuy.gg and displays the following error message.
![image](https://github.com/Aninuscsalas/wynncraft-101/assets/64874028/5755a4d7-5fc6-4452-9641-becac8996e5c)

After updating wynntils the pack works as expected, not sure why the pack ships with an older version of wynntils and not sure why it only causes an issue after the first launch.

**Comment by aninusmuffin** [comment]
Fixed in [1.0.2](https://modrinth.com/modpack/wynncraft/version/1.0.2)
