### ISSUE TITLE
Providing multiple "distributions" of the pack

### ISSUE THREAD

**Issue by sofiedotcafe** [Aninuscsalas/wynncraft-101#21]
Hey!

I also have an project focusing on improving the Wynncraft Experience, as you know.
It basically this pack but adds just a little bit more of those QOL mods.

The question would be, since we both have our own packs, would combining them be good?

Though, mine is still i 1.19,4 (I haven't had the time to maintain it), it would be probably a good addition (At least once ported to the newer versions)?

**Comment by aninusmuffin** [comment]
Sorry for the late response. 

I'm not sure if this is a good idea... I don't really like the idea of having multiple packs under the same modrinth page. 
Providing multiple distributions of the pack can create confusion around what the player should download.

**Comment by jh-devv** [comment]
> Sorry for the late response. 
> 
> I'm not sure if this is a good idea... I don't really like the idea of having multiple packs under the same modrinth page. 
> Providing multiple distributions of the pack can create confusion around what the player should download.

@Aninuscsalas 

What about splitting it for another pack, the maintenance for mine is painful to be honest?

Maybe a fork of yours with just the additions from mine? Could you do the maintenance? 😅
