### ISSUE TITLE
Initialization stuff

### ISSUE THREAD

**Issue by sofiedotcafe** [Aninuscsalas/wynncraft-101#4]
> 2. **Set Up Secrets and Permissions**
>   - Navigate to "Settings" -> "Secrets" and add the following secrets:
>     - `MODRINTH_TOKEN`, `MODRINTH_ID` for Modrinth authentication.
>     - `CURSEFORGE_TOKEN`, `CURSEFORGE_ID` for CurseForge authentication.
>   - Enable "Allow GitHub Actions to create and approve pull requests" under "Settings" -> "Actions" -> "General" -> "Workflow permissions".

You would need to do this!

**Comment by aninusmuffin** [comment]
done, btw can the changelogs be fixed or should i just edit it after the 0.1.0 published on modrinth?

**Comment by sofiedotcafe** [comment]
> done, btw can the changelogs be fixed or should i just edit it after the 0.1.0 published on modrinth?

Yea, what about it
What do you want to do :3 ?

**Comment by aninusmuffin** [comment]
> Yea, what about it What do you want to do :3 ?

This should be the changelog  https://github.com/Aninuscsalas/wynncraft-101-old/blob/main/quilt/CHANGELOG.mde
Can the changelog be set manually?

**Comment by sofiedotcafe** [comment]
> > Yea, what about it What do you want to do :3 ?
> 
> This should be the changelog https://github.com/Aninuscsalas/wynncraft-101-old/blob/main/quilt/CHANGELOG.mde Can the changelog be set manually?

Yea, you can change that and if you wantm also the pr body!
